# This matrix workflow is a master workflow which creates a strategy matrix and passes it to another self-written reusable workflow.
# It is a workaround to have more than one job using the same strategy matrix and thus building upon each other.

name: SIMPA Matrix Workflow

on:
  # run workflow on pushes to the main or develop branch
  push:
    branches: [ main, develop ]
  # and on all pull requests to the main or develop branch
  pull_request:
    branches: [ main, develop ]
  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:
  # Additionally, run Friday morning 6AM, so that we can react quickly if things break
  schedule:
  - cron: "0 5 * * 5"

jobs:
  create-version-matrix:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    uses: ./github/workflows/automatic_testing.yml # calls reusable automatic_testing workflow
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}

