# Uploads the current version of the package to PyPI when commit are pushed to main (including merges via pull requests)

name: Upload to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    if: github.repository == 'IMSY-DKFZ/simpa'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          python_version: '3.10'
